---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openappsec
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: openappsec-secret
    creationPolicy: Owner
  data:
    - secretKey: AGENT_TOKEN
      remoteRef:
        key: OpenAppSec
        property: KUBERNETES_AGENT_TOKEN
