---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./configuration/ks.yaml
  - ./snapshot/ks.yaml
  - ./volsync/ks.yaml
  # - ./filebrowser/ks.yaml
  - ./minio/ks.yaml
  - ./opencloud/ks.yaml
  - ./forgejo/ks.yaml
  - ./rustfs/ks.yaml
