---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-operator
  namespace: flux-system
spec:
  interval: 1h
  path: "./apps/monitoring/grafana/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: github-repo
  wait: false # no flux ks dependents
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 1h
  path: "./apps/monitoring/grafana/instance"
  prune: true
  sourceRef:
    kind: GitRepository
    name: github-repo
  wait: false # no flux ks dependents
  dependsOn:
    - name: external-secrets-stores
    - name: grafana-operator
